import hashlib
from urllib.parse import quote


def build_shot_prompt(shot) -> str:
    """Build a human-readable prompt for generated shot visuals."""
    parts = [
        getattr(shot, "image_prompt", None),
        getattr(shot, "title", None),
        getattr(shot, "description", None),
        getattr(shot, "shot_type", None),
        getattr(shot, "camera_angle", None),
        getattr(shot, "lens", None),
    ]
    prompt = " • ".join(part.strip() for part in parts if part and str(part).strip())
    return prompt or "Storyboard frame"


def generate_storyboard_image(prompt: str, seed: str, label: str = "Generated visual") -> str:
    """Return a deterministic SVG data URL for a shot visual."""
    digest = hashlib.sha256(seed.encode("utf-8")).hexdigest()
    primary = f"#{digest[:6]}"
    secondary = f"#{digest[6:12]}"
    accent = f"#{digest[12:18]}"
    prompt_lines = _wrap_text(prompt, 34)[:4]

    prompt_svg = "".join(
        f'<text x="32" y="{146 + (index * 28)}" fill="#f8f8ff" font-size="22" font-family="Arial, sans-serif">{_escape_xml(line)}</text>'
        for index, line in enumerate(prompt_lines)
    )

    svg = f"""
    <svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720">
      <defs>
        <linearGradient id="bg" x1="0%" x2="100%" y1="0%" y2="100%">
          <stop offset="0%" stop-color="{primary}" />
          <stop offset="100%" stop-color="{secondary}" />
        </linearGradient>
      </defs>
      <rect width="1280" height="720" fill="url(#bg)" />
      <circle cx="1050" cy="120" r="160" fill="{accent}" fill-opacity="0.22" />
      <rect x="24" y="24" width="1232" height="672" rx="24" fill="#060612" fill-opacity="0.34" stroke="#ffffff" stroke-opacity="0.2" />
      <text x="32" y="76" fill="#ffffff" font-size="28" font-family="Arial, sans-serif" font-weight="700">{_escape_xml(label)}</text>
      {prompt_svg}
      <text x="32" y="670" fill="#ffffff" fill-opacity="0.7" font-size="18" font-family="Arial, sans-serif">CineForge autogenerated storyboard visual</text>
    </svg>
    """.strip()
    return f"data:image/svg+xml;charset=utf-8,{quote(svg)}"


def shot_storyboard_image(shot) -> str:
    existing = getattr(shot, "storyboard_image", None)
    if existing:
        return existing

    prompt = build_shot_prompt(shot)
    seed = getattr(shot, "id", None) or f"{getattr(shot, 'scene_id', '')}:{prompt}"
    label = getattr(shot, "title", None) or "Generated visual"
    return generate_storyboard_image(prompt=prompt, seed=seed, label=label)


def shot_version_image(version) -> str:
    shot = getattr(version, "shot", None)
    prompt = build_shot_prompt(shot) if shot is not None else "Storyboard frame"
    label = f"Version {getattr(version, 'version_number', 1)}"
    seed = getattr(version, "id", None) or f"{getattr(version, 'shot_id', '')}:{getattr(version, 'version_number', 1)}"
    return generate_storyboard_image(prompt=prompt, seed=seed, label=label)


def _wrap_text(text: str, line_length: int) -> list[str]:
    words = text.split()
    if not words:
        return [text]

    lines = []
    current = words[0]
    for word in words[1:]:
        candidate = f"{current} {word}"
        if len(candidate) <= line_length:
            current = candidate
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines


def _escape_xml(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )
